name:                HashedExpression
version:             0.0.9
github:              "McMasterU/HashedExpression"
license:             BSD3
author:              "OCA & McMaster Start Coding"
maintainer:          "anandc@mcmaster.ca"
copyright:           "2019 OCA"


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Computing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/McMasterU/HashedExpression#readme>

dependencies:
  - base 
  - utility-ht
  - containers
  - text
  - array
  - deepseq
  - process
  - time
  - split
  - extra
  - mtl
  - filepath
  - file-embed
  - graphviz
  - nlopt-haskell
  - vector
  - primitive


extra-source-files:
  - ChangeLog.md


default-extensions:
  - OverloadedStrings
  - GADTs
  - OverloadedStrings
  - FlexibleContexts
  - FlexibleInstances
  - TypeFamilies
  - TypeApplications
  - StandaloneDeriving
  - TypeSynonymInstances
  - FunctionalDependencies
  - AllowAmbiguousTypes
  - RoleAnnotations
  - UndecidableInstances
  - ExtendedDefaultRules
  - MultiParamTypeClasses
  - TemplateHaskell
  - QuasiQuotes
  - ScopedTypeVariables
  - TupleSections
  - GeneralisedNewtypeDeriving
  - DataKinds
  - InstanceSigs
  - RecordWildCards
  - LambdaCase
  - PolyKinds
  - NoStarIsType
  - TypeOperators
  - ConstraintKinds

library:
  source-dirs:
    - src



executables:
  HashedExpression-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HashedExpression
      - hspec


tests:
  HashedExpression-test:
    main:                Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HashedExpression
      - hspec
      - process
      - HUnit
      - QuickCheck
