name:                HashedExpression
version:             0.0.6
github:              "McMasterU/HashedExpression"
license:             BSD3
author:              "OCA & McMaster Start Coding"
maintainer:          "anandc@mcmaster.ca"
copyright:           "2019 OCA"


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/McMasterU/HashedExpression#readme>

dependencies:
  - base 
  - utility-ht
  - containers
  - text
  - bytestring
  - array
  - deepseq
  - process
  - binary
  - time
  - split
  - extra
  - easyplot
  - mtl
  - filepath
  - file-embed

extra-source-files:
  - symphony/*.hs
  - ChangeLog.md

build-tools:
  - alex
  - happy

default-extensions:
  - OverloadedStrings
  - GADTs
  - OverloadedStrings
  - FlexibleContexts
  - FlexibleInstances
  - TypeFamilies
  - TypeApplications
  - StandaloneDeriving
  - TypeSynonymInstances
  - FunctionalDependencies
  - AllowAmbiguousTypes
  - RoleAnnotations
  - UndecidableInstances
  - ExtendedDefaultRules
  - MultiParamTypeClasses
  - TemplateHaskell
  - QuasiQuotes
  - ScopedTypeVariables
  - TupleSections
  - GeneralisedNewtypeDeriving
  - DataKinds
  - InstanceSigs
  - RecordWildCards
  - LambdaCase
  - PolyKinds

library:
  source-dirs:
    - src



executables:
  HashedExpression-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HashedExpression
      - hspec
  symphony:
    main:                Main.hs
    source-dirs:
      - symphony
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HashedExpression
      - regex-posix
      - optparse-applicative
      - JuicyPixels
      - process


tests:
  HashedExpression-test:
    main:                Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HashedExpression
      - hspec
      - process
      - HUnit
      - string-interpolate
      - QuickCheck
