name:                HashedExpression
version:             0.1.0.0
github:              "githubuser/HashedExpression"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/HashedExpression#readme>

dependencies:
  - base >= 4.7 && < 5
  - QuickCheck
  - utility-ht
  - containers
  - text
  - bytestring
  - array
  - deepseq
  - process
  - binary
  - time
  - split
  - extra
  - easyplot
  - string-quote
  - mtl

extra-source-files:
  - lang/*.hs
  - ChangeLog.md

build-tools:
  - alex
  - happy

default-extensions:
  - FlexibleContexts
  - RecordWildCards

library:
  source-dirs:
    - src
    - embed
  default-extensions:
    - OverloadedStrings
    - GADTs
    - OverloadedStrings
    - FlexibleContexts
    - FlexibleInstances
    - TypeFamilies
    - TypeApplications
    - StandaloneDeriving
    - TypeSynonymInstances
    - FunctionalDependencies
    - AllowAmbiguousTypes
    - RoleAnnotations
    - UndecidableInstances
    - ExtendedDefaultRules
    - MultiParamTypeClasses
    - TemplateHaskell
    - DeriveAnyClass
    - QuasiQuotes
    - ScopedTypeVariables
    - TupleSections
    - DataKinds
    - InstanceSigs
    - RecordWildCards
    - LambdaCase
    - PolyKinds
  exposed-modules:
    - HashedExpression.CollectDifferential
    - HashedExpression.Derivative
    - HashedExpression.Expression
    - HashedExpression.Hash
    - HashedExpression.Inner
    - HashedExpression.Interp
    - HashedExpression.Node
    - HashedExpression.Normalize
    - HashedExpression.Operation
    - HashedExpression.Pattern
    - HashedExpression.Plot
    - HashedExpression.Prettify
    - HashedExpression.Solver
    - HashedExpression.ToC
    - HashedExpression.Utils
    - HashedExpression.Var
    - FFTW



executables:
  HashedExpression-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HashedExpression
      - hspec
  symphony:
    main:                Main.hs
    source-dirs:         lang
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HashedExpression
      - regex-posix

tests:
  HashedExpression-test:
    main:                Spec.hs
    source-dirs:
      - test
      - src
      - embed
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - process
      - uuid
      - HUnit
    default-extensions:
      - OverloadedStrings
      - GADTs
      - OverloadedStrings
      - FlexibleContexts
      - FlexibleInstances
      - TypeFamilies
      - TypeApplications
      - StandaloneDeriving
      - TypeSynonymInstances
      - FunctionalDependencies
      - AllowAmbiguousTypes
      - RoleAnnotations
      - UndecidableInstances
      - ExtendedDefaultRules
      - MultiParamTypeClasses
      - TemplateHaskell
      - DeriveAnyClass
      - QuasiQuotes
      - ScopedTypeVariables
      - TupleSections
      - DataKinds
      - InstanceSigs
      - RecordWildCards
      - LambdaCase
      - PolyKinds
