-- Haskell data types for the abstract syntax.
-- Generated by the BNF converter.

module AbsHashedLang where

data Exp
    = EAdd Exp Exp
    | ESub Exp Exp
    | EMul Exp Exp
    | EDiv Exp Exp
    | EInt Integer
  deriving (Eq, Ord, Show, Read)

